### ISSUE TITLE
Possible to indent between headings

### ISSUE THREAD

**Issue by jerudnik** [melat0nin/zotero-roam-export#18]
Really appreciate this tool - I'm curious if there's an ability (might not be thinking creatively enough) to indent extracted annotations between underlined headings.

**Comment by melat0nin** [comment]
The addon doesn't do this, although I appreciate it would be useful. The challenge is the number of edge cases -- not everyone uses underline to denote a heading, etc etc. I agree thought it would be worth having as something that can be enabled optionally. I'll think about how it might be achieved.

**Comment by jerudnik** [comment]
Makes sense - thanks for the thought!

**Comment by melat0nin** [comment]
The problem here (which I'm running into myself quite frequently) is that it requires you to underline every heading under which you add a highlight or annotation, otherwise you end up with indented highlights/annotations that don't belong to the supposed parent heading. This might be counterproductive in terms of clarity of the structure of the notes -- highlights will appear to be related to headings (by indentation) which they are not actually related to within the source document.

I'm not sure how to get round this reliably 🤔

**Comment by jerudnik** [comment]
Yep - working with on a paper now that has some sub-headings where I don't have anything written. Not sure there's an easy / worthwhile solution
