### ISSUE TITLE
Change in the output layout?

### ISSUE THREAD

**Issue by richardlm** [melat0nin/zotero-roam-export#20]
Hi

I don't know if you have seen the discussion on twitter between Conor White-Sullivan, Cortex Future and Nat Eliason (+ others) about the best way to use attributes (Saturday 1st August, c.21:00 BST)?

I can't say I full understand the implications of the many variations that are suggested in the multiple threads, but I think the general thrust is that putting attributes as blocks under a 'metadata' heading may not be the best solution for the long term in Roam.

The couple of examples I saw posted seem to have the attributes in a single block, presumably with soft returns, e.g. Cortex Futura:
![image](https://user-images.githubusercontent.com/15072925/89124515-87ce8980-d4cf-11ea-8cc4-92c1700b088c.png)

Conor introduces what looks to me like complex nesting, e.g. [[[[Author]] : [[Author1]] [[Author2]]]], but I lose the plot at that point.

Rather worrying that the design of what seems to be a core part of the system is still not settled yet, but I guess that's part of the cult!

**Comment by melat0nin** [comment]
Your example on the left is basically the same as the exporter at present (there's no nested attributes, as far as I can see). I'm not sure what the value of that would be, except to filter on all items authored by both `Author A` and `Author B` (but you could do that via Roam's filters anyway, so it seems unnecessarily complicated to embed that schema in the export).

**Comment by richardlm** [comment]
The key difference that I was wondering about was that the example appears to use soft returns within the block. So all of the metadata fields are in one block rather than in separate blocks as with the exporter.  I read in the past (but cannot now find the source) that this enables more effective querying - is this something you have looked at?

**Comment by melat0nin** [comment]
Ah I see it now. This is potentially interesting but I'm not clear on what the value is -- I'd need to see a concrete example of why it's better than separated attribute blocks in order to implement this, particularly since it would mean a break from existing export formats.

I suppose the intention is that query results will show the full metadata block rather than just the single attribute and value, but I wonder if that's a red herring in terms of attribute atomism -- retaining granular attributes but instead focusing on altering how the query's result are shown might be a more fruitful way to go. I've seen some discussion on Slack about the latter, e.g. showing not just the result block but also the title or surrounding blocks from the resulting page.

**Comment by richardlm** [comment]
That suggestion makes a lot of sense. I'd much rather know that I have captured the granularity as it gives greatest flexibility in handling and presenting it. And I would guess it is the most future-proof, unless Roam Research does something totally wacky with attributes!
Thanks - I'll close this.
